spring.application.name=JForceOnlineStrore

spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/jforcestore
spring.datasource.username=root
spring.datasource.password=Root2207

spring.jpa.hibernate.ddl-auto=update